// <auto-generated />
using System;
using Hooked.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hooked.Shared.Migrations
{
    [DbContext(typeof(HookedDbContext))]
    [Migration("20260314080128_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hooked.Shared.Data.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("Hooked.Shared.Data.CatchComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CommentedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CatchId");

                    b.HasIndex("CommentedAt");

                    b.HasIndex("UserId");

                    b.ToTable("CatchComments");
                });

            modelBuilder.Entity("Hooked.Shared.Data.CatchReaction", b =>
                {
                    b.Property<Guid>("CatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReactedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CatchId", "UserId");

                    b.HasIndex("ReactedAt");

                    b.HasIndex("UserId");

                    b.ToTable("CatchReactions");
                });

            modelBuilder.Entity("Hooked.Shared.Data.CatchRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CaughtAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("LengthMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationJson")
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CaughtAt");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("UserId");

                    b.ToTable("CatchRecords");
                });

            modelBuilder.Entity("Hooked.Shared.Data.FishDexEntry", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<int>("CatchCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRare")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PersonalBestCatchId")
                        .HasColumnType("uuid");

                    b.Property<double?>("PersonalBestLengthMeters")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "SpeciesId");

                    b.HasIndex("PersonalBestCatchId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("UnlockedAt");

                    b.ToTable("FishDexEntries");
                });

            modelBuilder.Entity("Hooked.Shared.Data.FishSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ConservationStatus")
                        .HasColumnType("text");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DiscoveredByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("IllustrationGeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IllustrationImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsEndangered")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInvasive")
                        .HasColumnType("boolean");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CommonName");

                    b.HasIndex("DiscoveredByUserId");

                    b.ToTable("FishSpecies");
                });

            modelBuilder.Entity("Hooked.Shared.Data.FriendRelation", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Since")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "FriendId");

                    b.HasIndex("FriendId");

                    b.ToTable("FriendRelations");
                });

            modelBuilder.Entity("Hooked.Shared.Data.LeaderboardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Score")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Category", "Score");

                    b.ToTable("LeaderboardEntries");
                });

            modelBuilder.Entity("Hooked.Shared.Data.Sighting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LocationJson")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReportedAt");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("UserId");

                    b.ToTable("Sightings");
                });

            modelBuilder.Entity("Hooked.Shared.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Hooked.Shared.Data.CatchComment", b =>
                {
                    b.HasOne("Hooked.Shared.Data.CatchRecord", "Catch")
                        .WithMany("Comments")
                        .HasForeignKey("CatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany("CatchComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.CatchReaction", b =>
                {
                    b.HasOne("Hooked.Shared.Data.CatchRecord", "Catch")
                        .WithMany("Reactions")
                        .HasForeignKey("CatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany("CatchReactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.CatchRecord", b =>
                {
                    b.HasOne("Hooked.Shared.Data.FishSpecies", "Species")
                        .WithMany("Catches")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany("Catches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.FishDexEntry", b =>
                {
                    b.HasOne("Hooked.Shared.Data.CatchRecord", "PersonalBestCatch")
                        .WithMany()
                        .HasForeignKey("PersonalBestCatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hooked.Shared.Data.FishSpecies", "Species")
                        .WithMany("FishDexEntries")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany("FishDexEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalBestCatch");

                    b.Navigation("Species");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.FishSpecies", b =>
                {
                    b.HasOne("Hooked.Shared.Data.User", "DiscoveredByUser")
                        .WithMany()
                        .HasForeignKey("DiscoveredByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DiscoveredByUser");
                });

            modelBuilder.Entity("Hooked.Shared.Data.FriendRelation", b =>
                {
                    b.HasOne("Hooked.Shared.Data.User", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany("Friends")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.LeaderboardEntry", b =>
                {
                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.Sighting", b =>
                {
                    b.HasOne("Hooked.Shared.Data.FishSpecies", "Species")
                        .WithMany("Sightings")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany("Sightings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.CatchRecord", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Hooked.Shared.Data.FishSpecies", b =>
                {
                    b.Navigation("Catches");

                    b.Navigation("FishDexEntries");

                    b.Navigation("Sightings");
                });

            modelBuilder.Entity("Hooked.Shared.Data.User", b =>
                {
                    b.Navigation("CatchComments");

                    b.Navigation("CatchReactions");

                    b.Navigation("Catches");

                    b.Navigation("FishDexEntries");

                    b.Navigation("Friends");

                    b.Navigation("Sightings");
                });
#pragma warning restore 612, 618
        }
    }
}
