// <auto-generated />
using System;
using Hooked.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hooked.Shared.Migrations
{
    [DbContext(typeof(HookedDbContext))]
    partial class HookedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hooked.Shared.Data.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("Hooked.Shared.Data.CatchComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CommentedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CatchId");

                    b.HasIndex("CommentedAt");

                    b.HasIndex("UserId");

                    b.ToTable("CatchComments");
                });

            modelBuilder.Entity("Hooked.Shared.Data.CatchReaction", b =>
                {
                    b.Property<Guid>("CatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReactedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CatchId", "UserId");

                    b.HasIndex("ReactedAt");

                    b.HasIndex("UserId");

                    b.ToTable("CatchReactions");
                });

            modelBuilder.Entity("Hooked.Shared.Data.CatchRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CaughtAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FishingSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<double?>("LengthMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationJson")
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CaughtAt");

                    b.HasIndex("FishingSessionId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsFavorite");

                    b.ToTable("CatchRecords");
                });

            modelBuilder.Entity("Hooked.Shared.Data.FishDexEntry", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<int>("CatchCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRare")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PersonalBestCatchId")
                        .HasColumnType("uuid");

                    b.Property<double?>("PersonalBestLengthMeters")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "SpeciesId");

                    b.HasIndex("PersonalBestCatchId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("UnlockedAt");

                    b.ToTable("FishDexEntries");
                });

            modelBuilder.Entity("Hooked.Shared.Data.FishSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ConservationStatus")
                        .HasColumnType("text");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DiscoveredByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("IllustrationGeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IllustrationImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsEndangered")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInvasive")
                        .HasColumnType("boolean");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CommonName");

                    b.HasIndex("DiscoveredByUserId");

                    b.ToTable("FishSpecies");
                });

            modelBuilder.Entity("Hooked.Shared.Data.FishingQuest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cadence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("RewardXp")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("SkillId");

                    b.HasIndex("Cadence", "IsActive");

                    b.ToTable("fishing_quests", (string)null);
                });

            modelBuilder.Entity("Hooked.Shared.Data.FishingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StartTime");

                    b.HasIndex("UserId");

                    b.ToTable("FishingSessions");
                });

            modelBuilder.Entity("Hooked.Shared.Data.FriendRelation", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Since")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "FriendId");

                    b.HasIndex("FriendId");

                    b.ToTable("FriendRelations");
                });

            modelBuilder.Entity("Hooked.Shared.Data.LeaderboardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Score")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Category", "Score");

                    b.ToTable("LeaderboardEntries");
                });

            modelBuilder.Entity("Hooked.Shared.Data.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AchievementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("CatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("TriggeredByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("CatchId");

                    b.HasIndex("TriggeredByUserId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Hooked.Shared.Data.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FishingSessionId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FishingSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Hooked.Shared.Data.PostPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("PostPhotos");
                });

            modelBuilder.Entity("Hooked.Shared.Data.Sighting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LocationJson")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReportedAt");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("UserId");

                    b.ToTable("Sightings");
                });

            modelBuilder.Entity("Hooked.Shared.Data.Skill", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("Hooked.Shared.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Hooked.Shared.Data.UserAchievement", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "AchievementId");

                    b.HasIndex("AchievementId");

                    b.HasIndex("EarnedAt");

                    b.HasIndex("UserId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("Hooked.Shared.Data.UserFishingQuestProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProgressCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RewardClaimedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RewardXpEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.HasIndex("RewardXpEventId");

                    b.HasIndex("UserId", "IsCompleted", "RewardClaimedAtUtc");

                    b.HasIndex("UserId", "PeriodStartUtc", "PeriodEndUtc");

                    b.HasIndex("UserId", "QuestId", "PeriodStartUtc")
                        .IsUnique();

                    b.ToTable("user_fishing_quest_progress", (string)null);
                });

            modelBuilder.Entity("Hooked.Shared.Data.UserSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentXp")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstAchievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalXpEarned")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LastUpdatedAt");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId", "SkillId")
                        .IsUnique();

                    b.ToTable("user_skills", (string)null);
                });

            modelBuilder.Entity("Hooked.Shared.Data.XpEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CatchRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("LevelsGained")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("NewLevel")
                        .HasColumnType("integer");

                    b.Property<int>("NewXp")
                        .HasColumnType("integer");

                    b.Property<int>("PreviousLevel")
                        .HasColumnType("integer");

                    b.Property<int>("PreviousXp")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("XpDelta")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CatchRecordId");

                    b.HasIndex("EventKey")
                        .IsUnique();

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId", "SkillId", "CreatedAt");

                    b.ToTable("xp_events", (string)null);
                });

            modelBuilder.Entity("Hooked.Shared.Data.CatchComment", b =>
                {
                    b.HasOne("Hooked.Shared.Data.CatchRecord", "Catch")
                        .WithMany("Comments")
                        .HasForeignKey("CatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany("CatchComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.CatchReaction", b =>
                {
                    b.HasOne("Hooked.Shared.Data.CatchRecord", "Catch")
                        .WithMany("Reactions")
                        .HasForeignKey("CatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany("CatchReactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.CatchRecord", b =>
                {
                    b.HasOne("Hooked.Shared.Data.FishingSession", "FishingSession")
                        .WithMany("Catches")
                        .HasForeignKey("FishingSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hooked.Shared.Data.FishSpecies", "Species")
                        .WithMany("Catches")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany("Catches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FishingSession");

                    b.Navigation("Species");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.FishDexEntry", b =>
                {
                    b.HasOne("Hooked.Shared.Data.CatchRecord", "PersonalBestCatch")
                        .WithMany()
                        .HasForeignKey("PersonalBestCatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hooked.Shared.Data.FishSpecies", "Species")
                        .WithMany("FishDexEntries")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany("FishDexEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalBestCatch");

                    b.Navigation("Species");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.FishSpecies", b =>
                {
                    b.HasOne("Hooked.Shared.Data.User", "DiscoveredByUser")
                        .WithMany()
                        .HasForeignKey("DiscoveredByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DiscoveredByUser");
                });

            modelBuilder.Entity("Hooked.Shared.Data.FishingQuest", b =>
                {
                    b.HasOne("Hooked.Shared.Data.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Hooked.Shared.Data.FishingSession", b =>
                {
                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany("FishingSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.FriendRelation", b =>
                {
                    b.HasOne("Hooked.Shared.Data.User", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany("Friends")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.LeaderboardEntry", b =>
                {
                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.Notification", b =>
                {
                    b.HasOne("Hooked.Shared.Data.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hooked.Shared.Data.CatchRecord", "Catch")
                        .WithMany()
                        .HasForeignKey("CatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hooked.Shared.Data.User", "TriggeredByUser")
                        .WithMany()
                        .HasForeignKey("TriggeredByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("Catch");

                    b.Navigation("TriggeredByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.Post", b =>
                {
                    b.HasOne("Hooked.Shared.Data.FishingSession", "FishingSession")
                        .WithMany()
                        .HasForeignKey("FishingSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FishingSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.PostPhoto", b =>
                {
                    b.HasOne("Hooked.Shared.Data.Post", "Post")
                        .WithMany("Photos")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Hooked.Shared.Data.Sighting", b =>
                {
                    b.HasOne("Hooked.Shared.Data.FishSpecies", "Species")
                        .WithMany("Sightings")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany("Sightings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.UserAchievement", b =>
                {
                    b.HasOne("Hooked.Shared.Data.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.UserFishingQuestProgress", b =>
                {
                    b.HasOne("Hooked.Shared.Data.FishingQuest", "Quest")
                        .WithMany("UserProgress")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hooked.Shared.Data.XpEvent", "RewardXpEvent")
                        .WithMany()
                        .HasForeignKey("RewardXpEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany("FishingQuestProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");

                    b.Navigation("RewardXpEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.UserSkill", b =>
                {
                    b.HasOne("Hooked.Shared.Data.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.XpEvent", b =>
                {
                    b.HasOne("Hooked.Shared.Data.CatchRecord", "CatchRecord")
                        .WithMany()
                        .HasForeignKey("CatchRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hooked.Shared.Data.Skill", "Skill")
                        .WithMany("XpEvents")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hooked.Shared.Data.User", "User")
                        .WithMany("XpEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatchRecord");

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hooked.Shared.Data.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("Hooked.Shared.Data.CatchRecord", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Hooked.Shared.Data.FishSpecies", b =>
                {
                    b.Navigation("Catches");

                    b.Navigation("FishDexEntries");

                    b.Navigation("Sightings");
                });

            modelBuilder.Entity("Hooked.Shared.Data.FishingQuest", b =>
                {
                    b.Navigation("UserProgress");
                });

            modelBuilder.Entity("Hooked.Shared.Data.FishingSession", b =>
                {
                    b.Navigation("Catches");
                });

            modelBuilder.Entity("Hooked.Shared.Data.Post", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Hooked.Shared.Data.Skill", b =>
                {
                    b.Navigation("UserSkills");

                    b.Navigation("XpEvents");
                });

            modelBuilder.Entity("Hooked.Shared.Data.User", b =>
                {
                    b.Navigation("CatchComments");

                    b.Navigation("CatchReactions");

                    b.Navigation("Catches");

                    b.Navigation("FishDexEntries");

                    b.Navigation("FishingQuestProgress");

                    b.Navigation("FishingSessions");

                    b.Navigation("Friends");

                    b.Navigation("Posts");

                    b.Navigation("Sightings");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserSkills");

                    b.Navigation("XpEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
