CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE TABLE "Achievements" (
        "Id" uuid NOT NULL,
        "Key" text NOT NULL,
        "Title" character varying(200) NOT NULL,
        "Description" character varying(1000),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Achievements" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" uuid NOT NULL,
        "Username" text NOT NULL,
        "DisplayName" character varying(100),
        "Email" character varying(254),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE TABLE "FishSpecies" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CommonName" character varying(200) NOT NULL,
        "ScientificName" character varying(200),
        "ConservationStatus" text,
        "IsInvasive" boolean NOT NULL,
        "IsEndangered" boolean NOT NULL,
        "DiscoveredAt" timestamp with time zone NOT NULL,
        "DiscoveredByUserId" uuid,
        "IllustrationImageUrl" character varying(1024),
        "IllustrationGeneratedAt" timestamp with time zone,
        CONSTRAINT "PK_FishSpecies" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FishSpecies_Users_DiscoveredByUserId" FOREIGN KEY ("DiscoveredByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE TABLE "FriendRelations" (
        "UserId" uuid NOT NULL,
        "FriendId" uuid NOT NULL,
        "Since" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_FriendRelations" PRIMARY KEY ("UserId", "FriendId"),
        CONSTRAINT "FK_FriendRelations_Users_FriendId" FOREIGN KEY ("FriendId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_FriendRelations_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE TABLE "LeaderboardEntries" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Category" text NOT NULL,
        "Score" bigint NOT NULL,
        "RecordedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_LeaderboardEntries" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LeaderboardEntries_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE TABLE "CatchRecords" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "SpeciesId" integer NOT NULL,
        "CaughtAt" timestamp with time zone NOT NULL,
        "LengthMeters" double precision,
        "WeightKg" double precision,
        "PhotoPath" character varying(512),
        "LocationJson" text,
        CONSTRAINT "PK_CatchRecords" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CatchRecords_FishSpecies_SpeciesId" FOREIGN KEY ("SpeciesId") REFERENCES "FishSpecies" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_CatchRecords_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE TABLE "Sightings" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "SpeciesId" integer NOT NULL,
        "ReportedAt" timestamp with time zone NOT NULL,
        "Note" text,
        "LocationJson" text,
        CONSTRAINT "PK_Sightings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Sightings_FishSpecies_SpeciesId" FOREIGN KEY ("SpeciesId") REFERENCES "FishSpecies" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Sightings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE TABLE "CatchComments" (
        "Id" uuid NOT NULL,
        "CatchId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "CommentText" character varying(500) NOT NULL,
        "CommentedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CatchComments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CatchComments_CatchRecords_CatchId" FOREIGN KEY ("CatchId") REFERENCES "CatchRecords" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CatchComments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE TABLE "CatchReactions" (
        "CatchId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "ReactedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CatchReactions" PRIMARY KEY ("CatchId", "UserId"),
        CONSTRAINT "FK_CatchReactions_CatchRecords_CatchId" FOREIGN KEY ("CatchId") REFERENCES "CatchRecords" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CatchReactions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE TABLE "FishDexEntries" (
        "UserId" uuid NOT NULL,
        "SpeciesId" integer NOT NULL,
        "UnlockedAt" timestamp with time zone NOT NULL,
        "IsRare" boolean NOT NULL,
        "CatchCount" integer NOT NULL,
        "PersonalBestLengthMeters" double precision,
        "PersonalBestCatchId" uuid,
        CONSTRAINT "PK_FishDexEntries" PRIMARY KEY ("UserId", "SpeciesId"),
        CONSTRAINT "FK_FishDexEntries_CatchRecords_PersonalBestCatchId" FOREIGN KEY ("PersonalBestCatchId") REFERENCES "CatchRecords" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_FishDexEntries_FishSpecies_SpeciesId" FOREIGN KEY ("SpeciesId") REFERENCES "FishSpecies" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_FishDexEntries_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Achievements_Key" ON "Achievements" ("Key");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE INDEX "IX_CatchComments_CatchId" ON "CatchComments" ("CatchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE INDEX "IX_CatchComments_CommentedAt" ON "CatchComments" ("CommentedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE INDEX "IX_CatchComments_UserId" ON "CatchComments" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE INDEX "IX_CatchReactions_ReactedAt" ON "CatchReactions" ("ReactedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE INDEX "IX_CatchReactions_UserId" ON "CatchReactions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE INDEX "IX_CatchRecords_CaughtAt" ON "CatchRecords" ("CaughtAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE INDEX "IX_CatchRecords_SpeciesId" ON "CatchRecords" ("SpeciesId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE INDEX "IX_CatchRecords_UserId" ON "CatchRecords" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE INDEX "IX_FishDexEntries_PersonalBestCatchId" ON "FishDexEntries" ("PersonalBestCatchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE INDEX "IX_FishDexEntries_SpeciesId" ON "FishDexEntries" ("SpeciesId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE INDEX "IX_FishDexEntries_UnlockedAt" ON "FishDexEntries" ("UnlockedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE INDEX "IX_FishSpecies_CommonName" ON "FishSpecies" ("CommonName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE INDEX "IX_FishSpecies_DiscoveredByUserId" ON "FishSpecies" ("DiscoveredByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE INDEX "IX_FriendRelations_FriendId" ON "FriendRelations" ("FriendId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE INDEX "IX_LeaderboardEntries_Category_Score" ON "LeaderboardEntries" ("Category", "Score");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE INDEX "IX_LeaderboardEntries_UserId" ON "LeaderboardEntries" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE INDEX "IX_Sightings_ReportedAt" ON "Sightings" ("ReportedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE INDEX "IX_Sightings_SpeciesId" ON "Sightings" ("SpeciesId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE INDEX "IX_Sightings_UserId" ON "Sightings" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314080128_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260314080128_InitialCreate', '10.0.4');
    END IF;
END $EF$;
COMMIT;

